# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Projects/C_CPP/crypto/checksum/checksum

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Projects/C_CPP/crypto/checksum/checksum

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/C_CPP/crypto/checksum/checksum/CMakeFiles /mnt/d/Projects/C_CPP/crypto/checksum/checksum//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/C_CPP/crypto/checksum/checksum/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crypto_checksum

# Build rule for target.
crypto_checksum: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto_checksum
.PHONY : crypto_checksum

# fast build rule for target.
crypto_checksum/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/build
.PHONY : crypto_checksum/fast

CheckSum.o: CheckSum.cpp.o

.PHONY : CheckSum.o

# target to build an object file
CheckSum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/CheckSum.cpp.o
.PHONY : CheckSum.cpp.o

CheckSum.i: CheckSum.cpp.i

.PHONY : CheckSum.i

# target to preprocess a source file
CheckSum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/CheckSum.cpp.i
.PHONY : CheckSum.cpp.i

CheckSum.s: CheckSum.cpp.s

.PHONY : CheckSum.s

# target to generate assembly for a file
CheckSum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/CheckSum.cpp.s
.PHONY : CheckSum.cpp.s

Crc32Sum.o: Crc32Sum.cpp.o

.PHONY : Crc32Sum.o

# target to build an object file
Crc32Sum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/Crc32Sum.cpp.o
.PHONY : Crc32Sum.cpp.o

Crc32Sum.i: Crc32Sum.cpp.i

.PHONY : Crc32Sum.i

# target to preprocess a source file
Crc32Sum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/Crc32Sum.cpp.i
.PHONY : Crc32Sum.cpp.i

Crc32Sum.s: Crc32Sum.cpp.s

.PHONY : Crc32Sum.s

# target to generate assembly for a file
Crc32Sum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/Crc32Sum.cpp.s
.PHONY : Crc32Sum.cpp.s

MD5Sum.o: MD5Sum.cpp.o

.PHONY : MD5Sum.o

# target to build an object file
MD5Sum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/MD5Sum.cpp.o
.PHONY : MD5Sum.cpp.o

MD5Sum.i: MD5Sum.cpp.i

.PHONY : MD5Sum.i

# target to preprocess a source file
MD5Sum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/MD5Sum.cpp.i
.PHONY : MD5Sum.cpp.i

MD5Sum.s: MD5Sum.cpp.s

.PHONY : MD5Sum.s

# target to generate assembly for a file
MD5Sum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/MD5Sum.cpp.s
.PHONY : MD5Sum.cpp.s

fileSum.o: fileSum.cpp.o

.PHONY : fileSum.o

# target to build an object file
fileSum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/fileSum.cpp.o
.PHONY : fileSum.cpp.o

fileSum.i: fileSum.cpp.i

.PHONY : fileSum.i

# target to preprocess a source file
fileSum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/fileSum.cpp.i
.PHONY : fileSum.cpp.i

fileSum.s: fileSum.cpp.s

.PHONY : fileSum.s

# target to generate assembly for a file
fileSum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto_checksum.dir/build.make CMakeFiles/crypto_checksum.dir/fileSum.cpp.s
.PHONY : fileSum.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... crypto_checksum"
	@echo "... CheckSum.o"
	@echo "... CheckSum.i"
	@echo "... CheckSum.s"
	@echo "... Crc32Sum.o"
	@echo "... Crc32Sum.i"
	@echo "... Crc32Sum.s"
	@echo "... MD5Sum.o"
	@echo "... MD5Sum.i"
	@echo "... MD5Sum.s"
	@echo "... fileSum.o"
	@echo "... fileSum.i"
	@echo "... fileSum.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

